// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: services.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Services_TrackHeartbeat_FullMethodName              = "/services.Services/TrackHeartbeat"
	Services_ClientToMasterUpload_FullMethodName        = "/services.Services/clientToMasterUpload"
	Services_ClientToDataKeeperUpload_FullMethodName    = "/services.Services/clientToDataKeeperUpload"
	Services_DataNodeNotifyMaster_FullMethodName        = "/services.Services/dataNodeNotifyMaster"
	Services_MasterToClientSuccessNotify_FullMethodName = "/services.Services/MasterToClientSuccessNotify"
	Services_DownloadFile_FullMethodName                = "/services.Services/DownloadFile"
	Services_MasterToDataKeeperReplica_FullMethodName   = "/services.Services/MasterToDataKeeperReplica"
	Services_NodeToNodeReplica_FullMethodName           = "/services.Services/NodeToNodeReplica"
)

// ServicesClient is the client API for Services service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServicesClient interface {
	TrackHeartbeat(ctx context.Context, opts ...grpc.CallOption) (Services_TrackHeartbeatClient, error)
	ClientToMasterUpload(ctx context.Context, in *ClientToMasterUploadRequest, opts ...grpc.CallOption) (*ClientToMasterUploadResponse, error)
	ClientToDataKeeperUpload(ctx context.Context, in *ClientToDataKeeperUploadRequest, opts ...grpc.CallOption) (*ClientToDataKeeperUploadResponse, error)
	DataNodeNotifyMaster(ctx context.Context, in *DataNodeNotificationRequest, opts ...grpc.CallOption) (*DataNodeNotificationResponse, error)
	MasterToClientSuccessNotify(ctx context.Context, in *MasterToClientSuccessNotifyRequest, opts ...grpc.CallOption) (*MasterToClientSuccessNotifyResponse, error)
	DownloadFile(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error)
	MasterToDataKeeperReplica(ctx context.Context, in *MasterToDataKeeperReplicaRequest, opts ...grpc.CallOption) (*MasterToDataKeeperReplicaResponse, error)
	NodeToNodeReplica(ctx context.Context, in *NodeToNodeReplicaRequest, opts ...grpc.CallOption) (*NodeToNodeReplicaResponse, error)
}

type servicesClient struct {
	cc grpc.ClientConnInterface
}

func NewServicesClient(cc grpc.ClientConnInterface) ServicesClient {
	return &servicesClient{cc}
}

func (c *servicesClient) TrackHeartbeat(ctx context.Context, opts ...grpc.CallOption) (Services_TrackHeartbeatClient, error) {
	stream, err := c.cc.NewStream(ctx, &Services_ServiceDesc.Streams[0], Services_TrackHeartbeat_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &servicesTrackHeartbeatClient{stream}
	return x, nil
}

type Services_TrackHeartbeatClient interface {
	Send(*HeartbeatRequest) error
	Recv() (*HeartbeatResponse, error)
	grpc.ClientStream
}

type servicesTrackHeartbeatClient struct {
	grpc.ClientStream
}

func (x *servicesTrackHeartbeatClient) Send(m *HeartbeatRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *servicesTrackHeartbeatClient) Recv() (*HeartbeatResponse, error) {
	m := new(HeartbeatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *servicesClient) ClientToMasterUpload(ctx context.Context, in *ClientToMasterUploadRequest, opts ...grpc.CallOption) (*ClientToMasterUploadResponse, error) {
	out := new(ClientToMasterUploadResponse)
	err := c.cc.Invoke(ctx, Services_ClientToMasterUpload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesClient) ClientToDataKeeperUpload(ctx context.Context, in *ClientToDataKeeperUploadRequest, opts ...grpc.CallOption) (*ClientToDataKeeperUploadResponse, error) {
	out := new(ClientToDataKeeperUploadResponse)
	err := c.cc.Invoke(ctx, Services_ClientToDataKeeperUpload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesClient) DataNodeNotifyMaster(ctx context.Context, in *DataNodeNotificationRequest, opts ...grpc.CallOption) (*DataNodeNotificationResponse, error) {
	out := new(DataNodeNotificationResponse)
	err := c.cc.Invoke(ctx, Services_DataNodeNotifyMaster_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesClient) MasterToClientSuccessNotify(ctx context.Context, in *MasterToClientSuccessNotifyRequest, opts ...grpc.CallOption) (*MasterToClientSuccessNotifyResponse, error) {
	out := new(MasterToClientSuccessNotifyResponse)
	err := c.cc.Invoke(ctx, Services_MasterToClientSuccessNotify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesClient) DownloadFile(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error) {
	out := new(DownloadResponse)
	err := c.cc.Invoke(ctx, Services_DownloadFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesClient) MasterToDataKeeperReplica(ctx context.Context, in *MasterToDataKeeperReplicaRequest, opts ...grpc.CallOption) (*MasterToDataKeeperReplicaResponse, error) {
	out := new(MasterToDataKeeperReplicaResponse)
	err := c.cc.Invoke(ctx, Services_MasterToDataKeeperReplica_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicesClient) NodeToNodeReplica(ctx context.Context, in *NodeToNodeReplicaRequest, opts ...grpc.CallOption) (*NodeToNodeReplicaResponse, error) {
	out := new(NodeToNodeReplicaResponse)
	err := c.cc.Invoke(ctx, Services_NodeToNodeReplica_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicesServer is the server API for Services service.
// All implementations must embed UnimplementedServicesServer
// for forward compatibility
type ServicesServer interface {
	TrackHeartbeat(Services_TrackHeartbeatServer) error
	ClientToMasterUpload(context.Context, *ClientToMasterUploadRequest) (*ClientToMasterUploadResponse, error)
	ClientToDataKeeperUpload(context.Context, *ClientToDataKeeperUploadRequest) (*ClientToDataKeeperUploadResponse, error)
	DataNodeNotifyMaster(context.Context, *DataNodeNotificationRequest) (*DataNodeNotificationResponse, error)
	MasterToClientSuccessNotify(context.Context, *MasterToClientSuccessNotifyRequest) (*MasterToClientSuccessNotifyResponse, error)
	DownloadFile(context.Context, *DownloadRequest) (*DownloadResponse, error)
	MasterToDataKeeperReplica(context.Context, *MasterToDataKeeperReplicaRequest) (*MasterToDataKeeperReplicaResponse, error)
	NodeToNodeReplica(context.Context, *NodeToNodeReplicaRequest) (*NodeToNodeReplicaResponse, error)
	mustEmbedUnimplementedServicesServer()
}

// UnimplementedServicesServer must be embedded to have forward compatible implementations.
type UnimplementedServicesServer struct {
}

func (UnimplementedServicesServer) TrackHeartbeat(Services_TrackHeartbeatServer) error {
	return status.Errorf(codes.Unimplemented, "method TrackHeartbeat not implemented")
}
func (UnimplementedServicesServer) ClientToMasterUpload(context.Context, *ClientToMasterUploadRequest) (*ClientToMasterUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientToMasterUpload not implemented")
}
func (UnimplementedServicesServer) ClientToDataKeeperUpload(context.Context, *ClientToDataKeeperUploadRequest) (*ClientToDataKeeperUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientToDataKeeperUpload not implemented")
}
func (UnimplementedServicesServer) DataNodeNotifyMaster(context.Context, *DataNodeNotificationRequest) (*DataNodeNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataNodeNotifyMaster not implemented")
}
func (UnimplementedServicesServer) MasterToClientSuccessNotify(context.Context, *MasterToClientSuccessNotifyRequest) (*MasterToClientSuccessNotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MasterToClientSuccessNotify not implemented")
}
func (UnimplementedServicesServer) DownloadFile(context.Context, *DownloadRequest) (*DownloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedServicesServer) MasterToDataKeeperReplica(context.Context, *MasterToDataKeeperReplicaRequest) (*MasterToDataKeeperReplicaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MasterToDataKeeperReplica not implemented")
}
func (UnimplementedServicesServer) NodeToNodeReplica(context.Context, *NodeToNodeReplicaRequest) (*NodeToNodeReplicaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeToNodeReplica not implemented")
}
func (UnimplementedServicesServer) mustEmbedUnimplementedServicesServer() {}

// UnsafeServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicesServer will
// result in compilation errors.
type UnsafeServicesServer interface {
	mustEmbedUnimplementedServicesServer()
}

func RegisterServicesServer(s grpc.ServiceRegistrar, srv ServicesServer) {
	s.RegisterService(&Services_ServiceDesc, srv)
}

func _Services_TrackHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServicesServer).TrackHeartbeat(&servicesTrackHeartbeatServer{stream})
}

type Services_TrackHeartbeatServer interface {
	Send(*HeartbeatResponse) error
	Recv() (*HeartbeatRequest, error)
	grpc.ServerStream
}

type servicesTrackHeartbeatServer struct {
	grpc.ServerStream
}

func (x *servicesTrackHeartbeatServer) Send(m *HeartbeatResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *servicesTrackHeartbeatServer) Recv() (*HeartbeatRequest, error) {
	m := new(HeartbeatRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Services_ClientToMasterUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientToMasterUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).ClientToMasterUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Services_ClientToMasterUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).ClientToMasterUpload(ctx, req.(*ClientToMasterUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Services_ClientToDataKeeperUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientToDataKeeperUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).ClientToDataKeeperUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Services_ClientToDataKeeperUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).ClientToDataKeeperUpload(ctx, req.(*ClientToDataKeeperUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Services_DataNodeNotifyMaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataNodeNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).DataNodeNotifyMaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Services_DataNodeNotifyMaster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).DataNodeNotifyMaster(ctx, req.(*DataNodeNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Services_MasterToClientSuccessNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MasterToClientSuccessNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).MasterToClientSuccessNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Services_MasterToClientSuccessNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).MasterToClientSuccessNotify(ctx, req.(*MasterToClientSuccessNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Services_DownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).DownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Services_DownloadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).DownloadFile(ctx, req.(*DownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Services_MasterToDataKeeperReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MasterToDataKeeperReplicaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).MasterToDataKeeperReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Services_MasterToDataKeeperReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).MasterToDataKeeperReplica(ctx, req.(*MasterToDataKeeperReplicaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Services_NodeToNodeReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeToNodeReplicaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicesServer).NodeToNodeReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Services_NodeToNodeReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicesServer).NodeToNodeReplica(ctx, req.(*NodeToNodeReplicaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Services_ServiceDesc is the grpc.ServiceDesc for Services service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Services_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.Services",
	HandlerType: (*ServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "clientToMasterUpload",
			Handler:    _Services_ClientToMasterUpload_Handler,
		},
		{
			MethodName: "clientToDataKeeperUpload",
			Handler:    _Services_ClientToDataKeeperUpload_Handler,
		},
		{
			MethodName: "dataNodeNotifyMaster",
			Handler:    _Services_DataNodeNotifyMaster_Handler,
		},
		{
			MethodName: "MasterToClientSuccessNotify",
			Handler:    _Services_MasterToClientSuccessNotify_Handler,
		},
		{
			MethodName: "DownloadFile",
			Handler:    _Services_DownloadFile_Handler,
		},
		{
			MethodName: "MasterToDataKeeperReplica",
			Handler:    _Services_MasterToDataKeeperReplica_Handler,
		},
		{
			MethodName: "NodeToNodeReplica",
			Handler:    _Services_NodeToNodeReplica_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TrackHeartbeat",
			Handler:       _Services_TrackHeartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services.proto",
}
